### ISSUE TITLE
[Blog] not visible on mobile

### ISSUE THREAD

**Issue by StanAngeloff** [partialconf/2017.partialconf.com#10]
U can do fixs?

![image](https://user-images.githubusercontent.com/93127/27039633-1f91fea8-4f97-11e7-931e-8eab9383d817.png)

**Comment by gsamokovarov** [comment]
I fix!

![img_5043](https://user-images.githubusercontent.com/604618/27188295-60ea40de-51f6-11e7-8657-d32e31d8f4c9.PNG)
